apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pri-a
  namespace: ap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ap-northeast-1a
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
